version: 2.1
# Use a package of configuration called an orb.
orbs:
    aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
    hello-world:  # Choose any name, such as `build`
        # The primary container, where your job's commands will run
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command

    create_infrastructure:  
    # The primary container, where your job's commands will run
      docker:
        - image: aws-cli/default
      steps:
        - checkout # check out the code in the project directory
        - aws-cli/setup:
            aws-access-key-id: AWS_ACCESS_KEY
            aws-secret-access-key: AWS_ACCESS_SECRET
            aws-region: AWS_REGION_NAME
        - run: 
            name: Create Cloudformation Stack
            command: aws cloudformation deploy --template-file template.yml
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
              --region us-east-1
# Sequential workflow
workflows:
    # Name the workflow
    myWorkflow:
      jobs:
        - hello-world
        - create_infrastructure